// Twist seeds: short creative prompts, one of which is picked (deterministically
// from the fusion key) and handed to the LLM as the seed of the fusion's idea.
// They push 656,000 fusions away from each other and away from the obvious.

export const TWIST_SEEDS: string[] = [
  'debt — gain power now, pay it back later',
  'resonance — things that ring and echo together',
  'inversion — turn an enemy strength into its weakness',
  'pilgrimage — the path itself matters; position along it changes things',
  'harvest — something is planted, grows, and is reaped',
  'clockwork — precise timing, gears, countdowns',
  'memory — it remembers what happened earlier this wave',
  'metamorphosis — something transforms once a condition is met',
  'tides — pushing and pulling in waves',
  'sacrifice — give something up for a bigger payoff',
  'orbit — things circling other things',
  'contagion — spreading from one enemy to many',
  'symbiosis — two effects that feed each other in a loop',
  'mirrors — reflections, copies and duplicates',
  'gravity well — pulling the crowd together, then punishing the crowd',
  'hunger — grows stronger the more it consumes',
  'lanterns — lights that reveal, mark and guide',
  'erosion — slowly wearing defences down until they break',
  'crystallization — enemies become brittle, then shatter',
  'migration — something travels along the path',
  'kindling — small sparks that become a big fire',
  'static charge — build up, then discharge all at once',
  'fermentation — a slow effect that becomes potent if left alone',
  'overflow — excess spills over onto others',
  'dominoes — chain reactions from one enemy to the next',
  'tethers — linking enemies together so they share fate',
  'vendetta — obsessively focusing one chosen enemy',
  'echo chamber — repeats that grow each time',
  'quarantine — isolating one enemy from the rest',
  'seasons — cycling between two modes',
  'pressure — builds and builds until it bursts',
  'bells — striking one rings the others',
  'constellations — lines and patterns between points',
  'tripwires — traps triggered by movement',
  'shadows — effects that follow enemies around',
  'gambit — a risky bet that can pay off hugely',
  'hourglass — time slowing, speeding and running out',
  'scavenger — feeding on the fallen',
  'fracture — breaking into smaller pieces',
  'magnetism — attracting and repelling',
  'undertow — dragging the leaders back',
  'cascade — a falling sequence of strikes',
  'brand — marking enemies now for a payoff later',
  'bloom — something opens outward in petals',
  'furnace — heat stored up and released',
  'requiem — the dead keep contributing',
  'stampede — punishing crowds and clumps',
  'duel — punishing single strong enemies',
  'vigil — waiting patiently pays off',
  'frenzy — speeding up while fighting',
  'prism — splitting one thing into many',
  'rust — weakening armour over time',
  'lightning rod — drawing everything to a single point',
  'spore cloud — lingering areas that do the work',
  'whirlpool — circular motion that traps',
  'comet — something falling from the sky',
  'boomerang fate — what goes out comes back changed',
  'choir — many small voices adding up',
  'keystone — one enemy holds the others together',
  'wildfire — spreads if left unchecked',
  'anchor — pinning enemies in place',
  'mint — turning damage into gold',
  'relay — passing energy from tower to tower',
  'nightfall — darkness that makes enemies vulnerable',
  'fuse — a delayed explosion the enemy carries',
  'swarm mind — many small units acting as one',
  'judgement — weighing enemies and punishing the worst',
  'bramble maze — the path grows hostile',
  'tidal lock — enemies locked to the tower\'s rhythm',
  'avalanche — small pushes that snowball',
  'ghosts — afterimages that repeat what happened',
  'overclock — running too hot, with a cooldown',
  'pollination — carrying an effect from one enemy to another',
  'eclipse — something blocks, then reveals',
  'forge — heating, hammering and tempering',
  'pinball — bouncing between enemies',
  'last stand — strongest when enemies are close to the exit',
  'first light — strongest against fresh arrivals',
  'bounty board — rewards for specific kills',
  'aftershock — a second hit after the first',
];
